---
title: "Session 5A"
output: html_notebook
---

#1
```{r importing the data} 
library(readxl)
library(dplyr)
library(ggplot2)

beverage_companies <- read_excel("D:/Data Science Projects/Excel/Statistics 101 Damodaran/Session 5A_1.xlsx") %>% select(1:3)
beverage_companies <- as.data.frame(beverage_companies)
names(beverage_companies)[2] <- "EvSales"
names(beverage_companies)[3] <- "OperatingMargin"
```

##1A
```{r correlation and covariance of dataset}
cor(beverage_companies[,2:3])
cov(beverage_companies[,2:3])

cov(beverage_companies$`EV/Sales`,beverage_companies$`Pre-tax operating margin`)

```
##1C
```{r scatterplot for the data}
beverage_companies %>% 
                    ggplot(mapping = aes(y = evsales, x = `operating margin`)) + 
                    geom_point() +
                    labs(title = "Scatterplot",
                         subtitle = "Pearson = 0.78665, N = 13",
                         x = "Pre-tax Operating Margin",
                         y = "EV/Sales") +
                    geom_smooth(method = "lm", se =F, col = "darkblue")
```

##1D
```{r}
mod <- lm(data = beverage_companies,formula = EvSales ~ OperatingMargin )
summary(mod)
```

##1E
```{r}
beverage_companies <- beverage_companies %>%
                    mutate(Predicted_EV_Sales = round(OperatingMargin*22.284 + 3.819,digits = 2)) %>%
                    mutate(Residual = round(Predicted_EV_Sales - EvSales,digits = 2)) %>% select(1:5)
names(beverage_companies)[4] <- "PredictedEvSales"
names(beverage_companies)[5] <- "Residual"
```

##1F
```{r}
#is the residuals normally distributed?
beverage_companies %>% ggplot(mapping =aes(x = OperatingMargin, y = Residual)) +
                    geom_point()
```

```{r}
library(xlsx)
write.xlsx(beverage_companies,"Session5A_1A.xlsx")
```

#2 The dataset below contains data on the PBV ratios and returns on equity (ROE) of insurance companies

##2a. Estimate the correlation and covariance between PBV and ROE
```{r}
USInsurance <- read_excel("USInsurance.xlsx")
names(USInsurance)[3] <- "ROE"

cov(USInsurance[,2:3])
cor(USInsurance[,2:3])
aov(data = USInsurance, formula = PBV ~ ROE)

#very low correlation
```

##2b. Create a scatter plot of PBV and ROE.
```{r}
USInsurance %>% ggplot(mapping = aes(ROE, PBV)) +
                    geom_point() +
                    labs(title = "Insurance Companies PBV vs ROE",
                         x = "Price to Book Value",
                         y = "Return on Equity") +
                    geom_smooth(method = "lm", se =F)
#no correlation
```

##2c. Run a regression of PBV against ROE
```{r}
summary(lm(USInsurance,formula = PBV ~ ROE))
```

##2d. Run the diagnostics on your regression residuals.
```{r}
USInsurance <- USInsurance %>% mutate(EstimatedPBV = round(1.9232 + 1.6190*ROE, digits = 2)) %>%
                    mutate(Residuals = round(EstimatedPBV - PBV, digits = 2))
USInsurance %>% ggplot(mapping = aes(Residuals)) +
                    geom_histogram(binwidth = 5)
#the residuals are not normally distributed
```
